### USERS ###
###
POST http://localhost:3000/api/register
Content-Type: application/json

{
"full_name": "Spygom",
"email": "laikom@spygas.lt",
"password": "secret123"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
"email": "labas@krabas.lt",
"password": "secret123"
}

### ACCOUNTS ###
###
POST http://localhost:3000/api/accounts
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzgyNzc3MywiZXhwIjoxNjUzODM4NTczfQ.6qwMhCXgoTiUroIhUhLVnd9-9bm87q9uHEHhZUsMYI4

{
"group_id": 2
}

###
GET http://localhost:3000/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzgyMzU0NiwiZXhwIjoxNjUzODM0MzQ2fQ.sdndDKdG5hp7prsay35PDd6sdvL74yAvFfIjg9tYSAQ

### BILLS ###
###
GET http://localhost:3000/api/bills/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzgyMzU0NiwiZXhwIjoxNjUzODM0MzQ2fQ.sdndDKdG5hp7prsay35PDd6sdvL74yAvFfIjg9tYSAQ

###
POST http://localhost:3000/api/bills
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzgyMzU0NiwiZXhwIjoxNjUzODM0MzQ2fQ.sdndDKdG5hp7prsay35PDd6sdvL74yAvFfIjg9tYSAQ

{
    "group_id": 2,
     "amount": 300,
     "description": "b*tches"
}

### GROUPS ###
###
GET http://localhost:3000/api/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzgyMzU0NiwiZXhwIjoxNjUzODM0MzQ2fQ.sdndDKdG5hp7prsay35PDd6sdvL74yAvFfIjg9tYSAQ

###
POST http://localhost:3000/api/groups
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzgyMzU0NiwiZXhwIjoxNjUzODM0MzQ2fQ.sdndDKdG5hp7prsay35PDd6sdvL74yAvFfIjg9tYSAQ

{
    "name": "Dovana Albertui"
}




