### USERS ###
###
POST http://localhost:3000/api/register
Content-Type: application/json

{
"full_name": "Spygom",
"email": "laikom@spygas.lt",
"password": "secret123"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
"email": "laikom@spygas.lt",
"password": "secret123"
}

### ACCOUNTS ###
###
POST http://localhost:3000/api/accounts
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzY2MzkwNiwiZXhwIjoxNjUzNjc0NzA2fQ.sE1MlZ7OWhW6Q_c5_hSrwkCjuys1r3cq6QYHETqeWUs

{
"group_id": 2
}

###
GET http://localhost:3000/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzY2MzkwNiwiZXhwIjoxNjUzNjc0NzA2fQ.sE1MlZ7OWhW6Q_c5_hSrwkCjuys1r3cq6QYHETqeWUs

### BILLS ###
###
GET http://localhost:3000/api/bills/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzY2MzkwNiwiZXhwIjoxNjUzNjc0NzA2fQ.sE1MlZ7OWhW6Q_c5_hSrwkCjuys1r3cq6QYHETqeWUs

###
POST http://localhost:3000/api/bills
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzY2MzkwNiwiZXhwIjoxNjUzNjc0NzA2fQ.sE1MlZ7OWhW6Q_c5_hSrwkCjuys1r3cq6QYHETqeWUs

{
    "group_id": 2,
     "amount": 300,
     "description": "b*tches"
}


